[package]
name = "marching-cubes-terrain"
version = "0.1.0"
authors = ["eric556 <enpie123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
bevy_mod_picking = "0.3"
bevy_4x_camera = "0.1.*"